INSERT INTO burgers (name) VALUES ('Fig Mac');
INSERT INTO burgers (name) VALUES ('Double Flopper');
INSERT INTO burgers (name) VALUES ('Green Eggs and Hamburger');
INSERT INTO burgers (name) VALUES ('Handburger');
INSERT INTO burgers (name) VALUES ('Yam Burger');
INSERT INTO burgers (name) VALUES ('Tim Tamburger');
INSERT INTO burgers (name) VALUES ('Spam Burger');
INSERT INTO burgers (name) VALUES ('Jean Claude van Damburger');
INSERT INTO burgers (name) VALUES ('Green Eggs and Hamburger');
INSERT INTO burgers (name) VALUES ('Clamburger');
INSERT INTO burgers (name) VALUES ('Lamburger');
INSERT INTO burgers (name) VALUES ('Jam Burger');
INSERT INTO burgers (name) VALUES ('Flamm Burger');